modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/walksanatora/HexTweaks/issues"
license = "MIT"

[[mods]]
modId = "hextweaks"
version = "${version}"
displayName = "HexTweaks"
authors = "walksanator"
description = '''
A mildly opniated HexCasting addon (although I will take responses)
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"