name: Run Gradle on commit
on:
  push:
    branches: [master]
jobs:
  gradle:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[build]')
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build
        run: ./gradlew build
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "outputs"
          path: "*/build/libs"
